---

- name: Initialise the Master node
  import_tasks: initialise-master.yml
  when: jenkins_farm_role == 'master'

- name: Initialise the Slave nodes
  import_tasks: initialise-slave.yml
  when: jenkins_farm_role == 'slave'

- name: Add Jenkins slave nodes
  include_tasks: add-slave.yml
  with_items: "{{ groups['jenkins_farm'] }}"
  loop_control:
    loop_var: node_name
  when: jenkins_farm_role == 'master'
    and hostvars[node_name]['jenkins_farm_role'] == 'slave'
