---

- name: Initialise the Master node
  include_tasks: initialise-master.yml
  when: jenkins_farm_role == 'master'
  notify: restart jenkins

- name: Initialise the Slave nodes
  include_tasks: initialise-slave.yml
  when: jenkins_farm_role == 'slave'

# ensure Jenkins is restarted if need be, by flushing the handlers
- name: "Meta: Flush handlers"
  meta: flush_handlers
  when: jenkins_farm_role == 'master'

# wait for Jenkins to be available again
- name: Wait for Jenkins to start up before proceeding.
  command: >
    curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/
  args:
    warn: false
  register: result
  until: >
    'stdout' in result
    and (
      (result.stdout.find("403 Forbidden") != -1)
      or (result.stdout.find("200 OK") != -1)
    )
    and result.stdout.find("Please wait while") == -1
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false
  check_mode: false
  when: jenkins_farm_role == 'master'

- name: Add Jenkins slave nodes
  include_tasks: add-slave.yml
  with_items: "{{ groups['jenkins_farm'] }}"
  loop_control:
    loop_var: node_name
  when: jenkins_farm_role == 'master'
    and hostvars[node_name]['jenkins_farm_role'] == 'slave'
