---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - ../role-stubs/defaults_geerlingguy.jenkins.yml

  roles:
    - role: dankempter.jenkins-config
      when: jenkins_farm_role == 'master'

    - role: ../../../
