---
- name: Converge
  hosts: all
  become: true
  vars_files:
    # - ../../defaults/main.yml
    - vars/main.yml

  roles:
    - role: geerlingguy.git
      become: true

    - role: dankempter.jenkins-config

    - role: ../../../
